### ISSUE TITLE
Parse Test files

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Swifteroid/Slang#1]
Hi, @ianbytchek I came across this excellent tool, but I was wondering on how I can parse the following file to get the test methods and also checking it is apart of XCTestCase class.

Output:
test class: ExampleUITests
tests: [testExamplePass, testExampleTag, testExampleFail]

```
private let sample = """
import XCTest

class ExampleUITests: XCTestCase {
    override func setUp() {
        XCUIApplication().launch()
    }

    func testExamplePass() {
        XCTAssert(true)
    }

    // @SmokeTest
    func testExampleTag() {
        let testCaseIdentifier = ["SmokeTest"]

       report(testCases: ["APP-T486"]) {
            XCTAssert(true)
        }
    }

    func testExampleFail() {
        XCTAssert(false)
    }
}
"""
```

**Comment by ianbytchek** [comment]
Something along these lines, paste it in the Slang playground:

```swift
import Slang

let sample = """
import XCTest

class ExampleUITests: XCTestCase {
    override func setUp() {
        XCUIApplication().launch()
    }

    func testExamplePass() {
        XCTAssert(true)
    }

    // @SmokeTest
    func testExampleTag() {
        let testCaseIdentifier = ["SmokeTest"]

       report(testCases: ["APP-T486"]) {
            XCTAssert(true)
        }
    }

    func testExampleFail() {
        XCTAssert(false)
    }
}
"""

let disassembly = try! Disassembly(File(sample))
let structureQuery = disassembly.query.structure
let testClasses = structureQuery.descendants(where: { $0.kind == .decl(.class) && $0.name.hasSuffix("Tests") })
let testMethods = testClasses.children(where: { $0.kind == .decl(.function(.method(.instance))) && $0.name.hasPrefix("test") } )

print(testClasses.all.compactMap({ $0.name }))
print(testMethods.all.compactMap({ $0.name }))
// ["ExampleUITests"]
// ["testExamplePass()", "testExampleTag()", "testExampleFail()"]
```

Let me know if that works? Let me know if you end up using it, I meant to do some improvements for awhile, so that might motivate me! :)

**Comment by Ashraf-Ali-aa** [comment]
thank you very much, also I have locally added swift package support to the project, I'll push it up after I play around with the APIs, cheers

**Comment by Ashraf-Ali-aa** [comment]
@ianbytchek that worked but it there a way to check if the class is a child class of `XCTestCase`?

**Comment by ianbytchek** [comment]
For that you'll need to revert to [SourceKitten](https://github.com/jpsim/SourceKitten) primitive value and dig into that:

```swift
import SourceKittenFramework
let testClasses = structureQuery.descendants(where: {
    guard $0.kind == .decl(.class) else { return false }
    guard $0.name.hasSuffix("Tests") else { return false }
    guard let inheritedTypes = $0.primitive[SwiftDocKey.inheritedtypes.rawValue] as? [[String: String]] else { return false }
    return inheritedTypes == [[SwiftDocKey.name.rawValue: "XCTestCase"]]
})
```

 Ideally we'd use a `Class` view, like there's a [`FunctionCall`](https://github.com/Swifteroid/Slang/blob/2927dc4d62f112662d1d33159db5f2ca5c5a13c3/source/Slang/View/View.Function.Call.swift) view, but I haven't had a chance to implement it yet.

Don't forget, this is all just a wrapper around SourceKitten, all queries have are based on a context object, which contain reference to a primitive type, in example with structure it's just a `[String: SourceKitRepresentable]` dictionary. To examine the query's primitives you can use `print(testClasses.all.map({ $0.primitive }))` or just `print(testClasses.all)` to access matched elements.

**Comment by Ashraf-Ali-aa** [comment]
Thank you 🏅
